import type { RouteSpec } from './routes';

const HEADER = `// AUTO-GENERATED by scripts/contracts-generate.mjs — DO NOT EDIT.
// 由 packages/contracts/src/routes.ts 生成；修改契约后运行 pnpm contracts:generate。
import { request, type CallArgs } from './request';

/** 统一 API 客户端：api.<routeId>({ params?, query?, body? }) */
export const api = {
`;

const FOOTER = `};
`;

/** 从路由契约生成 api-client 源码（纯函数，可做确定性测试） */
export function buildClientSource(routes: RouteSpec[]): string {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const r of routes) {
    if (seen.has(r.id)) throw new Error(`路由 id 重复，无法生成: ${r.id}`);
    seen.add(r.id);
    lines.push(`  /** ${r.summary} · ${r.method} ${r.path} · ${r.auth}${r.permission ? ' · ' + r.permission : ''} */`);
    lines.push(`  ${r.id}: (args: CallArgs = {}) => request('${r.method}', '${r.path}', args),`);
  }
  return `${HEADER}${lines.join('\n')}\n${FOOTER}`;
}
