/**
 * E2E 用例库（T11.2 · 仅编写，运行归本地测试阶段 · L1–L9 分层）。
 *
 * L1–L9 映射（依据《开发任务规划》验收分层；以负责人验收走查为准）：
 *   L1 登录闸门 · L2 生命链核心 · L3 首页面板 · L4 资讯与创作 · L5 探索活动
 *   L6 用品导购 · L7 家庭共享 · L8 管理链 · L9 合规与闭环
 */

export type End = 'web' | 'mobile' | 'admin' | 'site';

export interface E2ECase {
  id: string;
  layer: 'L1' | 'L2' | 'L3' | 'L4' | 'L5' | 'L6' | 'L7' | 'L8' | 'L9';
  end: End;
  title: string;
  steps: string[];
  expected: string[];
  refs: string[]; // 验收/需求编号（U## / #nn / BR-##）
  runtimeOnly?: boolean; // 依赖运行时（本地阶段执行）
}

export const E2E_CASES: E2ECase[] = [
  // ---- L1 登录闸门 ----
  {
    id: 'E-L1-01',
    layer: 'L1',
    end: 'web',
    title: '手机号验证码登录与协议闸门',
    steps: ['打开 /login', '输入手机号但不勾协议 → 点获取验证码', '勾选两协议 → 获取验证码', '输入 dev 码 123456 登录', '登录后回到登录前 deep-link（/pets/new）'],
    expected: ['协议未勾时阻断并提示', '验证码步骤可达', '登录成功进入首页', '回跳到原 deep-link 而非首页（U93 白名单）'],
    refs: ['U30', 'U93'],
    runtimeOnly: true,
  },
  {
    id: 'E-L1-02',
    layer: 'L1',
    end: 'web',
    title: '方案甲年龄分支与监护人不可绕',
    steps: ['注册填 <14 岁出生日期', '进入监护人页', '不完成验证直接访问 /pets'],
    expected: ['进入监护人同意流程', '未同意被 L1 闸门拦回', '微信登录同样被拦（U83）'],
    refs: ['U30', 'U83'],
    runtimeOnly: true,
  },
  {
    id: 'E-L1-03',
    layer: 'L1',
    end: 'mobile',
    title: '移动登录与 4-Tab 激活',
    steps: ['H5 打开 /#/login', '双勾协议 + 手机号登录', '观察底部 4-Tab', '切换 Tab 返回再进'],
    expected: ['登录成功前无 Tab 内私有数据', '4-Tab 出现（首页/宠物/探索/我的）', '切 Tab 保留各自栈'],
    refs: ['U50', 'U51'],
    runtimeOnly: true,
  },
  // ---- L2 生命链核心 ----
  {
    id: 'E-L2-01',
    layer: 'L2',
    end: 'web',
    title: '建档 4 步 → 首条记录 → 曲线 → 摘要',
    steps: ['登录后 /pets/new 走 4 步（物种/信息/照片跳过/体重）', '进入详情 → ＋记录·体重', '查看曲线页', '生成健康摘要（勾选模块）'],
    expected: ['四步校验逐步放行', '记录出现在时间线', '曲线显示数据点+趋势', '摘要标注静态快照与缺项（#35，仅所有者）'],
    refs: ['U31', 'U79'],
    runtimeOnly: true,
  },
  {
    id: 'E-L2-02',
    layer: 'L2',
    end: 'web',
    title: '疫苗记录 → 自动提醒 → 待办完成（X01）',
    steps: ['记录疫苗（发生日期+下次提醒）', '打开提醒中心', '完成待办 → 确认', '再次完成同一待办'],
    expected: ['自动生成下一次提醒', '待办置顶于首页（L3）', '成功显示处理人/记录/下期', '第二次完成显示家人已完成·不重复写入（U57）'],
    refs: ['U31', 'U57'],
    runtimeOnly: true,
  },
  {
    id: 'E-L2-03',
    layer: 'L2',
    end: 'web',
    title: '体重 10% 二次确认 / 5% 趋势高亮',
    steps: ['基线 10kg 录入 11kg', '录入 10.4kg', '查看曲线趋势标记'],
    expected: ['11kg 触发二次确认提示', '10.4kg 不触发确认但趋势高亮（≥5%）', '存储单位始终 kg（斤仅为展示）'],
    refs: ['U31', 'BR-07'],
    runtimeOnly: true,
  },
  {
    id: 'E-L2-04',
    layer: 'L2',
    end: 'mobile',
    title: '一键记录 Sheet 与记成功动效',
    steps: ['首页点「一键记录」', 'Sheet 上滑打开后快速下滑', '选择体重 → 保存', '观察成功动画'],
    expected: ['Sheet 位移≥120px 或快速下滑关闭', '表单校验与 Web 同口径', '业务成功后才播放成功动效（闭环§4）'],
    refs: ['U51', 'U54'],
    runtimeOnly: true,
  },
  // ---- L3 首页面板 ----
  {
    id: 'E-L3-01',
    layer: 'L3',
    end: 'web',
    title: '首页区块顺序与待办置顶',
    steps: ['登录无待办打开首页', '制造一条明日到期提醒', '刷新首页', '退出登录再看'],
    expected: ['无待办不制造紧急感', '提醒条置顶且先于宠物区', '未登录出现登录引导、隐藏宠物/记录区', '游客区块（资讯/用品/探索）仍可见'],
    refs: ['U32', '#7'],
    runtimeOnly: true,
  },
  {
    id: 'E-L3-02',
    layer: 'L3',
    end: 'mobile',
    title: '移动首页三卡 + 用品并入',
    steps: ['打开 H5 首页', '检查待办条/宠物卡/一键记录', '滚动到用品分区与资讯分区'],
    expected: ['L3 锚点齐全', '用品在首页而非第 5 Tab（决议）', '离线时顶部出现未同步横幅'],
    refs: ['U50', 'U51'],
    runtimeOnly: true,
  },
  {
    id: 'E-L3-03',
    layer: 'L3',
    end: 'site',
    title: '官网首页 CTA 与四板块',
    steps: ['打开官网 /', '检查 hero 双 CTA/四板块/产品矩阵', '点击页脚备案占位与合规链接'],
    expected: ['CTA 指向 /download 或场景页', '四板块齐全', '页脚含 ICP 占位与举报版权通道'],
    refs: ['U45'],
    runtimeOnly: true,
  },
  // ---- L4 资讯与创作 ----
  {
    id: 'E-L4-01',
    layer: 'L4',
    end: 'web',
    title: '投稿全链：草稿→提交→时间线→发布/驳回',
    steps: ['/write 写文章（触发 30s 自动存）', '提交审核', '我的投稿看时间线', '模拟驳回 3 次', '查看状态回跳 resume'],
    expected: ['自动存提示出现', '四步时间线推进', '3 次驳回显示暂停 7 天且不计违规（U76）', '状态操作后回到原任务'],
    refs: ['U33', 'U34'],
    runtimeOnly: true,
  },
  {
    id: 'E-L4-02',
    layer: 'L4',
    end: 'web',
    title: '疾病健康频道免责与评论机审可见性',
    steps: ['频道切到疾病健康', '打开文章看文末', '发正常评论', '（模拟）机审 SUSPECT 评论查看可见性'],
    expected: ['文末出现免责声明', '正常评论公开', 'SUSPECT 仅作者可见、REJECT 双不可见（U16）'],
    refs: ['U33'],
    runtimeOnly: true,
  },
  {
    id: 'E-L4-03',
    layer: 'L4',
    end: 'web',
    title: '搜索高亮与空结果兜底',
    steps: ['/search 输入「猫粮」', '输入无结果词'],
    expected: ['命中词高亮（单/多命中）', '空结果显示兜底推荐文案（U17）'],
    refs: ['U33', 'U17'],
    runtimeOnly: true,
  },
  // ---- L5 探索活动 ----
  {
    id: 'E-L5-01',
    layer: 'L5',
    end: 'web',
    title: '场所筛选 → 详情 → 导航计数 → 评价',
    steps: ['地图页选类型+5km', '进详情点导航', '写评价（全 5 分短文）', '同日再评同一场所'],
    expected: ['筛选参数合法（非法半径回落 5）', '导航点击计数 +1（L5 转化）', '全 5 短文预告人工复审（防刷）', '同场所当日仅 1 条（1 天 1 条）'],
    refs: ['U35', 'U81'],
    runtimeOnly: true,
  },
  {
    id: 'E-L5-02',
    layer: 'L5',
    end: 'web',
    title: '活动报名 8 拒因与告知同意',
    steps: ['活动页点立即报名', '不勾同意点确认', '勾选后报名成功', '（切换状态）截止后尝试报名', '查看我的报名取消'],
    expected: ['未勾同意被拒（CONSENT_REQUIRED）', '成功后有同意凭证记录', '截止后显示对应中文拒因（U69）', '取消前有后果说明（X10）'],
    refs: ['U68', 'U69'],
    runtimeOnly: true,
  },
  {
    id: 'E-L5-03',
    layer: 'L5',
    end: 'web',
    title: '领养信息无报名/交易按钮',
    steps: ['活动页切到领养 Tab', '查看领养卡操作区', '（模拟）发现售卖信息点举报'],
    expected: ['无报名按钮、无交易按钮（U90）', '红色风险提示与核验建议展示', '举报类型含 SELLING_SUSPECTED'],
    refs: ['U90'],
    runtimeOnly: true,
  },
  // ---- L6 用品导购 ----
  {
    id: 'E-L6-01',
    layer: 'L6',
    end: 'web',
    title: '禁品类三通道不可入库',
    steps: ['/goods 分类浏览', '（管理端）单条创建「肾脏处方粮」', 'CSV 导入含兽药行', '标签建库尝试'],
    expected: ['三通道均被同一黑名单拦截（U77）', 'CSV 逐行计拒绝原因', '前端详情兜底展示不可用文案'],
    refs: ['U23', 'U77'],
    runtimeOnly: true,
  },
  {
    id: 'E-L6-02',
    layer: 'L6',
    end: 'web',
    title: '下架 vs 治理清除的引用差异',
    steps: ['商品 A 普通下架', '商品 B 治理清除', '查看关联清单与评测引用'],
    expected: ['A：历史内容保留 + 已下架标（U88）', 'B：去敏感展示', '全不可用清单禁新发'],
    refs: ['U88'],
    runtimeOnly: true,
  },
  // ---- L7 家庭共享 ----
  {
    id: 'E-L7-01',
    layer: 'L7',
    end: 'web',
    title: '逐动作权限与只读可见性',
    steps: ['所有者共享宠物给家人=可管理', '家人登录看详情', '家人尝试编辑记录/生成摘要/调整档位', '查看未共享宠物深链'],
    expected: ['可管理可编辑记录+处理提醒', '摘要导出入口对非所有者隐藏（#35）', '档位调整被拒（U61）', '未共享深链先拒绝页不渲染数据（#31）'],
    refs: ['U61', '#31', '#35'],
    runtimeOnly: true,
  },
  {
    id: 'E-L7-02',
    layer: 'L7',
    end: 'web',
    title: '邀请加入范围声明与一人一家庭',
    steps: ['生成邀请码（7 天）', '另一账号已是家庭成员时输入码加入', '新账号加入并阅读范围声明'],
    expected: ['已是成员被拒（一人一家庭）', '范围声明展示三条边界（#40）', '新成员默认只读'],
    refs: ['U61', '#40'],
    runtimeOnly: true,
  },
  {
    id: 'E-L7-03',
    layer: 'L7',
    end: 'web',
    title: '所有权转移 24h 与管理员转交独立',
    steps: ['危险区发起宠物转移', '等待/模拟超 24h', '发起管理员转交', '接收方退出家庭'],
    expected: ['转移显示影响清单+可撤销', '超时失效且所有权不变（U62）', '转交与转移互不联动', '接收方退出→转交申请失效'],
    refs: ['U62'],
    runtimeOnly: true,
  },
  // ---- L8 管理链 ----
  {
    id: 'E-L8-01',
    layer: 'L8',
    end: 'admin',
    title: '审核工作台：SLA/锁/批量/快捷键',
    steps: ['审核员登录看侧栏过滤', '等 24h+ 行观察 SLA 色', 'A 领取行后 B 尝试操作', '选两行批量通过', '快捷键 A/R/Enter/Esc'],
    expected: ['无权限项不显示（rbac/audit）', '24h 红 48h 升级', 'B 被处理中锁拦截', '批量仅同类型无锁定行', '快捷键生效（§5）'],
    refs: ['U40', 'U41'],
    runtimeOnly: true,
  },
  {
    id: 'E-L8-02',
    layer: 'L8',
    end: 'admin',
    title: '封禁高危双保险与申诉闭环',
    steps: ['对目标发 L2 封禁（不勾二次确认）', '勾选后执行', '用户侧发起申诉', '管理员 48h 内结论'],
    expected: ['未二次确认被拒', '处置写审计（高危标记）', '申诉成立撤销处置剔除计数（U76）', '超 48h 看板标逾期'],
    refs: ['U43', 'U42'],
    runtimeOnly: true,
  },
  {
    id: 'E-L8-03',
    layer: 'L8',
    end: 'admin',
    title: '角色保存白名单与审计区间',
    steps: ['自定义角色勾 32 外权限点保存', '勾合法权限保存', '审计页选 >90 天区间查询'],
    expected: ['非法权限被拒并列出', '合法角色保存成功且留痕', '区间 >90 天被拒'],
    refs: ['U44'],
    runtimeOnly: true,
  },
  // ---- L9 合规与闭环 ----
  {
    id: 'E-L9-01',
    layer: 'L9',
    end: 'site',
    title: '分享页四态与登录回跳',
    steps: ['打开 /share/article/x?state=PUBLISHED', '切 TAKEDOWN/DRAFT/REJECTED/DELETED', '点登录 CTA'],
    expected: ['已发布：卡片与文章卡同构+来源标注（U92/U94）', '四态各有不可用文案', 'TAKEDOWN 态提供申诉入口', '登录回跳为站内白名单路径'],
    refs: ['U94', 'U92'],
    runtimeOnly: true,
  },
  {
    id: 'E-L9-02',
    layer: 'L9',
    end: 'web',
    title: '注销两维依赖 + 冷静期撤销确认',
    steps: ['持有共享宠物/家庭管理员/报名时打开注销页', '按入口处理依赖', '提交注销', '冷静期内直接登录（不点撤销）', '点击确认撤销'],
    expected: ['依赖四类各给实际入口（#53）', '处理后方可提交', '冷静期 15 天', '单纯登录不自动撤销', '点击确认才恢复'],
    refs: ['U48', '#53'],
    runtimeOnly: true,
  },
  {
    id: 'E-L9-03',
    layer: 'L9',
    end: 'mobile',
    title: '离线记录与冲突双选（#32）',
    steps: ['断网后记录体重', '查看记录状态', '恢复联网制造冲突', '选择覆盖（未确认前观察）'],
    expected: ['离线显示未同步而非已完成', '队列出现待同步项', '冲突页只给两选项', '未经确认绝不自动覆盖'],
    refs: ['U55', '#32'],
    runtimeOnly: true,
  },
  {
    id: 'E-L9-04',
    layer: 'L9',
    end: 'admin',
    title: '运行异常待办逾期升级（闭环§3）',
    steps: ['制造 >24h 未处理清理失败待办', '查看待办列表', '点升级'],
    expected: ['逾期项标记升级主管', '显示失败原因与重试入口', '不出现仅「已运行」的占位展示'],
    refs: ['U91'],
    runtimeOnly: true,
  },
];
