-- cutePet explore-service · V3：机构认证（U89）
CREATE TABLE org_credentials (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  state VARCHAR(16) NOT NULL DEFAULT 'NONE',          -- NONE/APPLY/APPROVED/REJECTED/EXPIRED/REVOKED
  material_path VARCHAR(255) NOT NULL DEFAULT '',     -- 材料不公开（U89）
  expires_at DATE NULL,
  reviewed_by BIGINT NULL,
  note VARCHAR(200) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
